// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var cpOptions = []prompt.Suggest{
	{Text: "-c", Description: "容器名称。如果省略，将选择 Pod 中的第一个容器。 "},
	{Text: "--container", Description: "容器名称。如果省略，将选择 Pod 中的第一个容器。 "},
	{Text: "--no-preserve", Description: "所复制的文件/目录的所有权和权限在容器中将不会被保留。 "},
}
