// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var rolloutStatusOptions = []prompt.Suggest{
	{Text: "-f", Description: "Filename, directory, or URL to files identifying the resource to get from a server."},
	{Text: "--filename", Description: "Filename, directory, or URL to files identifying the resource to get from a server."},
	{Text: "-R", Description: "Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests organized within the same directory."},
	{Text: "--recursive", Description: "Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests organized within the same directory."},
	{Text: "--revision", Description: "Pin to a specific revision for showing its status. Defaults to 0 (last revision)."},
	{Text: "-w", Description: "Watch the status of the rollout until it's done."},
	{Text: "--watch", Description: "Watch the status of the rollout until it's done."},
}
