// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configGetContextsOptions = []prompt.Suggest{
	{Text: "--no-headers", Description: "在使用默认或自定义列的输出格式时，不打印标题（默认会打印标题）。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  name"},
	{Text: "--output", Description: "输出格式。其中之一 :  name"},
}
