// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/elk-language/go-prompt"
)

var annotateOptions = []prompt.Suggest{
	{Text: "--all", Description: "选择指定资源类型所在命名空间中的所有资源，包括未初始化的资源。 "},
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将会发送的对象，而不实际发送。 "},
	{Text: "--field-selector", Description: "选择器（字段查询）用于筛选，支持 '='、'==' 和 '!=' 。（例如：--field-selector key1=value1,key2=value2）。服务器针对每种类型仅支持有限数量的字段查询。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于标识要更新注解的资源 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于标识要更新注解的资源 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--local", Description: "如果为真，注解将不会联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--overwrite", Description: "如果为真，则允许覆盖注释，否则拒绝覆盖现有注释的注释更新。 "},
	{Text: "--record", Description: "在资源注解中记录当前的 kubectl 命令。若设置为 false，则不记录命令。若设置为 true，则记录命令。若未设置，默认仅在已有注解值的情况下更新现有注解值。 "},
	{Text: "-R", Description: "对在 -f、--filename 中使用的目录进行递归处理。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "对在 -f、--filename 中使用的目录进行递归处理。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--resource-version", Description: "如果不为空，只有当这是对象的当前资源版本时，注解更新才会成功。仅在指定单个资源时有效。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--template", Description: "当 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
