// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var execOptions = []prompt.Suggest{
	{Text: "-c", Description: "Container name. If omitted, the first container in the pod will be chosen"},
	{Text: "--container", Description: "Container name. If omitted, the first container in the pod will be chosen"},
	{Text: "-p", Description: "Pod name"},
	{Text: "--pod", Description: "Pod name"},
	{Text: "-i", Description: "Pass stdin to the container"},
	{Text: "--stdin", Description: "Pass stdin to the container"},
	{Text: "-t", Description: "Stdin is a TTY"},
	{Text: "--tty", Description: "Stdin is a TTY"},
}
