// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/elk-language/go-prompt"
)

var convertOptions = []prompt.Suggest{
	{Text: "--allow-missing-template-keys", Description: "如果为真，在模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "-f", Description: "文件名、目录或需要转换的文件的 URL 。 "},
	{Text: "--filename", Description: "文件名、目录或需要转换的文件的 URL 。 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--local", Description: "如果为真，convert（转换）将不会尝试联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output-version", Description: "输出具有给定组版本的格式化对象（例如 ） :  'extensions/v1beta1')."},
	{Text: "-R", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--template", Description: "当 -o=go-template 或 -o=go-template-file 时，用于使用的模板字符串或模板文件的路径。模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
	{Text: "--validate", Description: "如果为真，则在发送输入之前使用模式对其进行验证 "},
}
