// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var cordonOptions = []prompt.Suggest{
	{Text: "--dry-run", Description: "如果为真，仅打印将被发送的对象，而不实际发送。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选 "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选 "},
}
