// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var setResourcesOptions = []prompt.Suggest{
	{Text: "--all", Description: "选择指定资源类型所在命名空间中的所有资源，包括未初始化的资源。 "},
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "-c", Description: "所选 Pod 模板中要更改的容器的名称，默认情况下会选择所有容器 - 可以使用通配符 "},
	{Text: "--containers", Description: "所选 Pod 模板中要更改的容器的名称，默认情况下会选择所有容器 - 可以使用通配符 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将会发送的对象，而不实际发送。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于确定要从服务器获取的资源。 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于确定要从服务器获取的资源。 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--limits", Description: "此容器的资源需求请求。例如，'cpu=100m,memory=256Mi'。请注意，服务器端组件可能会根据服务器配置（例如限制范围）分配请求。 "},
	{Text: "--local", Description: "如果为真，设置资源将不会联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--record", Description: "在资源注释中记录当前的 kubectl 命令。如果设置为 false ，则不记录命令。如果设置为 true ，则记录命令。如果未设置，默认情况下仅在已存在注释值时更新现有注释值。 "},
	{Text: "-R", Description: "对在 -f、--filename 中使用的目录进行递归处理。在您想要管理组织在同一目录内的相关清单时很有用。 "},
	{Text: "--recursive", Description: "对在 -f、--filename 中使用的目录进行递归处理。在您想要管理组织在同一目录内的相关清单时很有用。 "},
	{Text: "--requests", Description: "此容器的资源需求请求。例如，'cpu=100m，memory=256Mi' 。请注意，服务器端组件可能会根据服务器配置（例如限制范围）分配请求。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--template", Description: "在 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 golang 模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
