// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var replaceOptions = []prompt.Suggest{
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--cascade", Description: "如果为真，则级联删除此资源所管理的资源（例如由 ReplicationController 创建的 Pod）。默认值为真。 "},
	{Text: "-f", Description: "用于替换资源时所使用的。 "},
	{Text: "--filename", Description: "用于替换资源时所使用的。 "},
	{Text: "--force", Description: "仅在宽限期为 0 时使用。如果为真，会立即从 API 中移除资源并绕过优雅删除。请注意，某些资源的立即删除可能会导致不一致或数据丢失，并且需要确认。 "},
	{Text: "--grace-period", Description: "以秒为单位的时间段，给予资源以优雅地终止。如果为负值则被忽略。设置为 1 表示立即关闭。只有在 --force 为 true（强制删除）时才能设置为 0 。 "},
	{Text: "-k", Description: "处理一个 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理一个 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--raw", Description: "向服务器发送 PUT 请求的原始 URI 。使用 kubeconfig 文件指定的传输方式。 "},
	{Text: "-R", Description: "对在 -f、--filename 中使用的目录进行递归处理。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "对在 -f、--filename 中使用的目录进行递归处理。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--save-config", Description: "如果为真，当前对象的配置将保存在其注解中。否则，注解将保持不变。当您未来想要对此对象执行 `kubectl apply` 时，此标志很有用。 "},
	{Text: "--template", Description: "在 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
	{Text: "--timeout", Description: "在放弃删除操作前等待的时长，零表示根据对象的大小确定超时时间 "},
	{Text: "--validate", Description: "如果为真，则在发送输入之前使用模式对其进行验证 "},
	{Text: "--wait", Description: "如果为真，在返回之前等待资源消失。这会等待终结器。 "},
}
