// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var setSubjectOptions = []prompt.Suggest{
	{Text: "--all", Description: "选择指定资源类型所在命名空间中的所有资源，包括未初始化的资源 "},
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将被发送的对象，而不实际发送它。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于更新主体的资源 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于更新主体的资源 "},
	{Text: "--group", Description: "要绑定到角色的组 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--local", Description: "如果为真，设置的主体将不会联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "-R", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理组织在同一目录中的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理组织在同一目录中的相关清单时很有用。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选，不包括未初始化的，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--serviceaccount", Description: "要绑定到角色的服务账号 "},
	{Text: "--template", Description: "在 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。模板格式为 golang 模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
