// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var drainOptions = []prompt.Suggest{
	{Text: "--delete-local-data", Description: "即使存在使用 emptyDir（当节点排空时将被删除的本地数据）的 Pod，也继续操作。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将要发送的对象，而不实际发送。 "},
	{Text: "--force", Description: "即使存在不由复制控制器、副本集、作业、守护进程集或有状态集管理的 Pod，也继续执行。 "},
	{Text: "--grace-period", Description: "每个 Pod 优雅终止的时间（以秒为单位）。如果为负数，则使用 Pod 中指定的默认值。 "},
	{Text: "--ignore-daemonsets", Description: "忽略由 DaemonSet 管理的 Pod。 "},
	{Text: "--pod-selector", Description: "用于在节点上筛选 Pod 的标签选择器 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选 "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选 "},
	{Text: "--timeout", Description: "在放弃之前等待的时长，零表示无限。 "},
}
