// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var authCanIOptions = []prompt.Suggest{
	{Text: "-A", Description: "如果为真，则在所有命名空间中检查指定的操作。 "},
	{Text: "--all-namespaces", Description: "如果为真，则在所有命名空间中检查指定的操作。 "},
	{Text: "--list", Description: "如果为真，则打印所有允许的操作。 "},
	{Text: "--no-headers", Description: "如果为真，则打印允许的操作，不打印标题。 "},
	{Text: "-q", Description: "如果为真，则抑制输出并仅返回退出代码。 "},
	{Text: "--quiet", Description: "如果为真，则抑制输出并仅返回退出代码。 "},
	{Text: "--subresource", Description: "子资源，例如 pod/log 或 deployment/scale "},
}
