// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configViewOptions = []prompt.Suggest{
	{Text: "--allow-missing-template-keys", Description: "如果为真，在模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--flatten", Description: "将生成的 kubeconfig 文件展平为自包含的输出（适用于创建可移植的 kubeconfig 文件） "},
	{Text: "--merge", Description: "合并 kubeconfig 文件的完整层次结构 "},
	{Text: "--minify", Description: "从输出中删除当前上下文未使用的所有信息 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--raw", Description: "显示原始字节数据 "},
	{Text: "--template", Description: "在 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
