// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configSetClusterOptions = []prompt.Suggest{
	{Text: "--embed-certs", Description: "在 kubeconfig 中为集群条目嵌入证书 "},
}
