// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var attachOptions = []prompt.Suggest{
	{Text: "-c", Description: "容器名称。如果省略，将选择 Pod 中的第一个容器 "},
	{Text: "--container", Description: "容器名称。如果省略，将选择 Pod 中的第一个容器 "},
	{Text: "--pod-running-timeout", Description: "等待至少一个 Pod 处于运行状态的时长（例如 5 秒、2 分钟或 3 小时，大于零） "},
	{Text: "-i", Description: "将标准输入传递到容器 "},
	{Text: "--stdin", Description: "将标准输入传递到容器 "},
	{Text: "-t", Description: "标准输入是一个终端设备（TTY） "},
	{Text: "--tty", Description: "标准输入是一个终端设备（TTY） "},
}
