// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var explainOptions = []prompt.Suggest{
	{Text: "--api-version", Description: "获取特定 API 版本的不同解释 "},
	{Text: "--recursive", Description: "打印字段的字段（目前仅支持 1 层深度） "},
}
