// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var exposeOptions = []prompt.Suggest{
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--cluster-ip", Description: "将分配给服务的群集 IP。留空以自动分配，或设置为“None”以创建无头服务。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将会被发送的对象，而不实际发送它。 "},
	{Text: "--external-ip", Description: "额外的外部 IP 地址（不由 Kubernetes 管理），服务可接受。如果此 IP 路由到某个节点，除了生成的服务 IP 外，服务还可以通过此 IP 访问。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于标识要暴露服务的资源 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于标识要暴露服务的资源 "},
	{Text: "--generator", Description: "要使用的 API 生成器的名称。有 2 种生成器 :  'service/v1' and 'service/v2'. The only difference between them is that service port in v1 is named 'default', while it is left unnamed in v2. Default is 'service/v2'."},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "-l", Description: "此调用所创建的服务要应用的标签。 "},
	{Text: "--labels", Description: "此调用所创建的服务要应用的标签。 "},
	{Text: "--load-balancer-ip", Description: "要分配给负载均衡器的 IP。如果为空，将创建并使用一个临时 IP（特定于云提供商）。 "},
	{Text: "--name", Description: "新创建对象的名称。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--overrides", Description: "内联的 JSON 覆盖项，用于生成的对象。如果此项非空，则用于覆盖生成的对象。要求对象提供有效的 apiVersion 字段。 "},
	{Text: "--port", Description: "服务应在其上提供服务的端口。如果未指定，则从被暴露的资源复制。 "},
	{Text: "--protocol", Description: "要创建的服务的网络协议。默认值是“TCP”。 "},
	{Text: "--record", Description: "在资源注释中记录当前的 kubectl 命令。如果设置为 false ，则不记录命令。如果设置为 true ，则记录命令。如果未设置，默认情况下仅在已存在注释值时更新现有注释值。 "},
	{Text: "-R", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--save-config", Description: "如果为真，当前对象的配置将保存在其注解中。否则，注解将保持不变。此标志在您未来想要对该对象执行 `kubectl apply` 时很有用。 "},
	{Text: "--selector", Description: "用于此服务的标签选择器。仅支持基于相等性的选择器需求。如果为空（默认值），则从复制控制器或副本集中推断选择器。 "},
	{Text: "--session-affinity", Description: "如果不为空，则将服务的会话亲和性设置为此；合法值 :  'None', 'ClientIP'"},
	{Text: "--target-port", Description: "容器上端口的名称或编号，服务应将流量导向该端口。可选。 "},
	{Text: "--template", Description: "当 -o=go-template 或 -o=go-template-file 时，要使用的模板字符串或模板文件的路径。模板格式为 golang 模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
	{Text: "--type", Description: "此服务的类型 :  ClusterIP, NodePort, LoadBalancer, or ExternalName. Default is 'ClusterIP'."},
}
