// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var diffOptions = []prompt.Suggest{
	{Text: "--field-manager", Description: "用于跟踪字段所有权的管理器的名称。 "},
	{Text: "-f", Description: "文件名、目录或包含要进行差异比较的配置的文件的 URL "},
	{Text: "--filename", Description: "文件名、目录或包含要进行差异比较的配置的文件的 URL "},
	{Text: "--force-conflicts", Description: "如果为真，服务器端应用将强制更改以应对冲突。 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "-R", Description: "递归处理在 -f 、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理在 -f 、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--server-side", Description: "如果为真，则 apply 操作在服务器端而非客户端运行。 "},
}
