// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var pluginListOptions = []prompt.Suggest{
	{Text: "--name-only", Description: "如果为真，仅显示每个插件的二进制名称，而非其完整路径 "},
}
