// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var labelOptions = []prompt.Suggest{
	{Text: "--all", Description: "选择指定资源类型所在命名空间中的所有资源，包括未初始化的资源 "},
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将被发送的对象，而不实际发送它。 "},
	{Text: "--field-selector", Description: "选择器（字段查询）用于筛选，支持 '='、'==' 和 '!=' 。（例如 --field-selector key1=value1,key2=value2）。服务器对每种类型仅支持有限数量的字段查询。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于标识要更新标签的资源 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于标识要更新标签的资源 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--list", Description: "如果为真，则显示给定资源的标签。 "},
	{Text: "--local", Description: "如果为真，label 将不会联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--overwrite", Description: "如果为真，则允许覆盖标签，否则拒绝覆盖现有标签的标签更新。 "},
	{Text: "--record", Description: "在资源注解中记录当前的 kubectl 命令。如果设置为 false，则不记录命令。如果设置为 true，则记录命令。如果未设置，默认情况下只有在已存在注解值时才更新现有值。 "},
	{Text: "-R", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--resource-version", Description: "如果不为空，仅当这是对象的当前资源版本时，标签更新才会成功。仅在指定单个资源时有效。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选，不包括未初始化的那些，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选，不包括未初始化的那些，支持 '='、'==' 和 '!=' 。（例如 -l key1=value1,key2=value2） "},
	{Text: "--template", Description: "当 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。模板格式为 golang 模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
