// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var autoscaleOptions = []prompt.Suggest{
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "--cpu-percent", Description: "所有 Pod 的目标平均 CPU 利用率（表示为请求 CPU 的百分比）。如果未指定或为负数，则将使用默认的自动缩放策略。 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将被发送的对象，而不发送它。 "},
	{Text: "-f", Description: "文件名、目录或 URL 到用于标识要自动缩放的资源的文件。 "},
	{Text: "--filename", Description: "文件名、目录或 URL 到用于标识要自动缩放的资源的文件。 "},
	{Text: "--generator", Description: "要使用的 API 生成器的名称。目前仅有 1 个生成器。 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--max", Description: "自动缩放器可设置的 Pod 数量上限。必需。 "},
	{Text: "--min", Description: "自动缩放器可设置的 Pod 数量下限。如果未指定或为负数，服务器将应用默认值。 "},
	{Text: "--name", Description: "新创建对象的名称。如果未指定，将使用输入资源的名称。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--record", Description: "在资源注解中记录当前的 kubectl 命令。如果设置为 false ，则不记录命令。如果设置为 true ，则记录命令。如果未设置，默认仅在已有注解值时更新现有值。 "},
	{Text: "-R", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理在 -f、--filename 中使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--save-config", Description: "如果为真，当前对象的配置将保存在其注解中。否则，注解将保持不变。当您将来想要对这个对象执行 kubectl apply 操作时，此标志很有用。 "},
	{Text: "--template", Description: "在 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
