// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var logsOptions = []prompt.Suggest{
	{Text: "--all-containers", Description: "获取 Pod 中所有容器的日志。 "},
	{Text: "-c", Description: "打印此容器的日志 "},
	{Text: "--container", Description: "打印此容器的日志 "},
	{Text: "-f", Description: "指定是否应流式传输日志。 "},
	{Text: "--follow", Description: "指定是否应流式传输日志。 "},
	{Text: "--ignore-errors", Description: "如果监视/跟踪 Pod 日志，允许出现的任何错误为非致命错误 "},
	{Text: "--insecure-skip-tls-verify-backend", Description: "跳过对请求获取日志的 kubelet 身份的验证。理论上，攻击者可能会返回无效的日志内容。如果您的 kubelet 服务证书已过期，您可能希望使用此选项。 "},
	{Text: "--limit-bytes", Description: "要返回的日志的最大字节数。默认没有限制。 "},
	{Text: "--max-log-requests", Description: "指定使用选择器时要跟踪的并发日志的最大数量。默认值为 5 。 "},
	{Text: "--pod-running-timeout", Description: "等待至少一个 Pod 处于运行状态的时长（例如 5 秒、2 分钟或 3 小时，大于零） "},
	{Text: "--prefix", Description: "为每条日志行添加日志源（Pod 名称和容器名称）作为前缀 "},
	{Text: "-p", Description: "如果为真，则打印 Pod 中容器的上一个实例（如果存在）的日志。 "},
	{Text: "--previous", Description: "如果为真，则打印 Pod 中容器的上一个实例（如果存在）的日志。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选。 "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选。 "},
	{Text: "--since", Description: "仅返回相对时间（如 5 秒、2 分钟或 3 小时）之后的日志。默认返回所有日志。since-time 和 since 只能使用其中之一。 "},
	{Text: "--since-time", Description: "仅返回特定日期（RFC3339 格式）之后的日志。默认为所有日志。since-time 和 since 只能使用其中一个。 "},
	{Text: "--tail", Description: "要显示的最近日志文件的行数。如果没有选择器，默认为 -1，否则显示所有日志行；如果提供了选择器，则默认为 10 。 "},
	{Text: "--timestamps", Description: "在日志输出的每一行中包含时间戳 "},
}
