// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var setEnvOptions = []prompt.Suggest{
	{Text: "--all", Description: "如果为真，则选择指定资源类型的命名空间中的所有资源 "},
	{Text: "--allow-missing-template-keys", Description: "如果为真，当模板中缺少字段或映射键时，忽略模板中的任何错误。仅适用于 golang 和 jsonpath 输出格式。 "},
	{Text: "-c", Description: "所选 Pod 模板中要更改的容器的名称 - 可以使用通配符 "},
	{Text: "--containers", Description: "所选 Pod 模板中要更改的容器的名称 - 可以使用通配符 "},
	{Text: "--dry-run", Description: "如果为真，仅打印将要发送的对象，而不实际发送。 "},
	{Text: "-e", Description: "为每个容器设置的环境变量指定一个键值对。 "},
	{Text: "--env", Description: "为每个容器设置的环境变量指定一个键值对。 "},
	{Text: "-f", Description: "文件名、目录或指向文件的 URL，用于更新环境的资源 "},
	{Text: "--filename", Description: "文件名、目录或指向文件的 URL，用于更新环境的资源 "},
	{Text: "--from", Description: "一种资源的名称，用于从中注入环境变量 "},
	{Text: "--keys", Description: "以逗号分隔的要从指定资源导入的键的列表 "},
	{Text: "-k", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--list", Description: "如果为真，则以标准格式显示环境和任何更改。当我们有 kubectl view env 时，此标志将被移除。 "},
	{Text: "--local", Description: "如果为真，设置环境变量将不会联系 API 服务器，而是在本地运行。 "},
	{Text: "-o", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--output", Description: "输出格式。其中之一 :  json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file."},
	{Text: "--overwrite", Description: "如果为真，则允许环境被覆盖，否则拒绝覆盖现有环境的更新。 "},
	{Text: "--prefix", Description: "要附加到变量名称的前缀 "},
	{Text: "-R", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理 -f 或 --filename 所使用的目录。在您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--resolve", Description: "如果为真，在列出变量时显示机密或配置映射的引用 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选 "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选 "},
	{Text: "--template", Description: "当 -o=go-template 或 -o=go-template-file 时使用的模板字符串或模板文件的路径。该模板格式为 Go 语言模板 [http] : //golang.org/pkg/text/template/#pkg-overview]."},
}
