// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var deleteOptions = []prompt.Suggest{
	{Text: "--all", Description: "删除指定资源类型所在命名空间中的所有资源，包括未初始化的资源。 "},
	{Text: "-A", Description: "如果存在，列出所有命名空间中的请求对象。即使使用 --namespace 指定，当前上下文中的命名空间也会被忽略。 "},
	{Text: "--all-namespaces", Description: "如果存在，列出所有命名空间中的请求对象。即使使用 --namespace 指定，当前上下文中的命名空间也会被忽略。 "},
	{Text: "--cascade", Description: "如果为真，则级联删除此资源管理的资源（例如由 ReplicationController 创建的 Pod）。默认值为真。 "},
	{Text: "--field-selector", Description: "选择器（字段查询）用于筛选，支持 '='、'==' 和 '!=' 。（例如 --field-selector key1=value1,key2=value2）。服务器每种类型仅支持有限数量的字段查询。 "},
	{Text: "-f", Description: "包含要删除的资源。 "},
	{Text: "--filename", Description: "包含要删除的资源。 "},
	{Text: "--force", Description: "仅在宽限期为 0 时使用。如果为真，会立即从 API 中删除资源并绕过优雅删除。请注意，立即删除某些资源可能会导致不一致或数据丢失，并且需要确认。 "},
	{Text: "--grace-period", Description: "以秒为单位的时间段，给予资源以优雅地终止。如果为负数则被忽略。设置为 1 表示立即关闭。只有在 --force 为 true（强制删除）时才能设置为 0 。 "},
	{Text: "--ignore-not-found", Description: "将“资源未找到”视为成功删除。当指定 --all 时，默认值为“true”。 "},
	{Text: "-k", Description: "处理一个 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--kustomize", Description: "处理一个 kustomization 目录。此标志不能与 -f 或 -R 一起使用。 "},
	{Text: "--now", Description: "如果为 true，资源会被立即发出关闭信号（与 --grace-period=1 相同）。 "},
	{Text: "-o", Description: "输出模式。使用“-o name”以获得更简短的输出（资源/名称）。 "},
	{Text: "--output", Description: "输出模式。使用“-o name”以获得更简短的输出（资源/名称）。 "},
	{Text: "--raw", Description: "向服务器发送 DELETE 请求的原始 URI 。使用 kubeconfig 文件指定的传输方式。 "},
	{Text: "-R", Description: "递归处理 -f 或 --filename 所使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "--recursive", Description: "递归处理 -f 或 --filename 所使用的目录。当您想要管理在同一目录中组织的相关清单时很有用。 "},
	{Text: "-l", Description: "选择器（标签查询）用于筛选，不包括未初始化的。 "},
	{Text: "--selector", Description: "选择器（标签查询）用于筛选，不包括未初始化的。 "},
	{Text: "--timeout", Description: "在放弃删除操作之前等待的时长，零表示根据对象的大小确定超时时间 "},
	{Text: "--wait", Description: "如果为真，在返回之前等待资源消失。这会等待终结器。 "},
}
