// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configSetOptions = []prompt.Suggest{
	{Text: "--set-raw-bytes", Description: "当编写 []byte 类型的 PROPERTY_VALUE 时，直接写入给定的字符串，无需进行 base64 解码。 "},
}
