name: Releasekube-prompt
env:
  GO_VERSION: 1.18.x
on:
  push:
    tags:
      - 'v*'

jobs:
  publishGitRelease:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: Unshallow repo
        run: git fetch --prune --unshallow

      - name: 设置go版本
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: 安装upx
        run: bash scripts/upxinstall.sh
#      - name: 生成发行说明草稿
#        id: release_notes
#        uses: release-drafter/release-drafter@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --verbose --clean --release-footer-tmpl=scripts/release/footer.md.tmpl --release-header-tmpl=scripts/release/head.md.tmpl
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}



#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ steps.release_notes.outputs.tag_name }}
#          release_name: ${{ steps.release_notes.outputs.release_name }}
#          body: ${{ steps.release_notes.outputs.body }}
#          files: build/*
#          draft: true
#          fail_on_unmatched_files: true